pref "extensions.zotero.translators.opds.citeCommand", "cite"
pref "extensions.zotero.translators.opds.citeKeyFormat", "[auth][year]"
pref "extensions.zotero.translators.opds.unicode", ""
pref "extensions.zotero.translators.opds.fancyURLs", false
pref "extensions.zotero.translators.opds.brace-all", true
pref "extensions.zotero.translators.opds.useprefix", false
pref "extensions.zotero.translators.opds.skipfields", ""
pref "services.sync.prefs.sync.extensions.zotero.translators.opds.citeCommand", true
pref "services.sync.prefs.sync.extensions.zotero.translators.opds.citeKeyFormat", true
pref "services.sync.prefs.sync.extensions.zotero.translators.opds.unicode", true
pref "services.sync.prefs.sync.extensions.zotero.translators.opds.brace-all", true
pref "services.sync.prefs.sync.extensions.zotero.translators.opds.useprefix", true
pref "services.sync.prefs.sync.extensions.zotero.translators.opds.skipfields", true
